import './globals.css'
import Navbar from './components/Navbar'
import { ReactNode } from "react";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: ReactNode;
};

export default function RootLayout( {children } :
  Props
 ) {
  return (
    <html lang="en">
      <body className="bg-slate-800">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
